# Generated by Django 3.1.1 on 2020-09-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctor_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user_id',
            new_name='user',
        ),
    ]
