# Generated by Django 3.1.1 on 2020-10-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
