# Generated by Django 3.1.1 on 2020-10-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0008_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
